### ISSUE TITLE
Change optional flag to match neofetch format

### ISSUE THREAD

**Issue by watthedoodle** [watthedoodle/hyperfetch#1]
At the moment we have an optional CLI flag called `ascii-distro` that is defined here:

https://github.com/watthedoodle/hyperfetch/blob/main/src/main.rs#L22

The argument parser we use is called "clap" see [Clap Docs](https://docs.rs/clap/latest/clap/).

This flag diverges from `neofetch` where it is simply `ascii_distro`.

Clap by default will convert underscores into dashes `-`.

There is most probably an override [attribute](https://doc.rust-lang.org/rust-by-example/attribute.html) that can be used to specify a custom flag name such that it is `ascii_distro` and not `ascii-distro`

**Comment by goodnewsj62** [comment]
Hi to be clear,  the goal is for the flag not to be converted into ascii-distro by clap @watthedoodle

**Comment by watthedoodle** [comment]
good work on `snake_case_fix` PR :+1: it's now merged so this issue is now resolved :)
